"""empty message

Revision ID: 30e958317a9c
Revises: 4c36013dbdc6
Create Date: 2021-12-22 13:52:35.839888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e958317a9c'
down_revision = '4c36013dbdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.String(length=150), nullable=False))
    op.drop_column('task', 'task_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_name', sa.VARCHAR(length=150), nullable=False))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###
